jobs:
- name: u14ruball-test
  type: runSh
  runtime:
    container: true
  steps:
    - TASK:
        runtime:
          options:
            imageName: "drydock/u14ruball"
            imageTag: master
        script:
         - source /etc/profile.d/rvm.sh
         - rvm list
         - ruby --version
